-- Create the table
create table grammar_rules (
  id bigint generated by default as identity primary key,
  pattern text,
  scenario text
);

-- Create an index for faster text searching on pattern
create index grammar_rules_pattern_idx on grammar_rules using gin(to_tsvector('english', pattern));

-- Enable Row Level Security (RLS) is generally good practice
alter table grammar_rules enable row level security;

-- Create a policy that allows anyone to read (Select)
create policy "Allow public read access"
on grammar_rules for select
using (true);

-- Create a policy that allows authenticated users (or service role) to insert/update
-- For the upload script, we will likely use the service key or user login, 
-- but ensuring we can write is key.
create policy "Allow full access for service role"
on grammar_rules
using ( auth.role() = 'service_role' )
with check ( auth.role() = 'service_role' );
